# Generated by Django 4.1.1 on 2022-09-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='category',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_room',
            field=models.CharField(choices=[('NOT', 'Not defined'), ('FIRST_C', '1-class'), ('SECOND_C', '2-class'), ('THIRD_C', '3-class'), ('FOURTH_C', '4-class')], default='Not defined', max_length=255, verbose_name='Class'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
