# Generated by Django 4.1.1 on 2022-09-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_remove_subject_category_alter_lesson_class_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(default=1, max_length=255, verbose_name='Lesson slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Subject slug'),
        ),
    ]
