# Generated by Django 4.1.1 on 2022-09-25 04:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_lesson_slug_alter_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='view',
            field=models.PositiveIntegerField(default=0, verbose_name='View'),
        ),
    ]
