# Generated by Django 4.1.1 on 2022-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_link',
            field=models.CharField(default=1, max_length=255, verbose_name='Video'),
            preserve_default=False,
        ),
    ]
