# Generated by Django 4.1.1 on 2022-09-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_lesson_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_link',
        ),
    ]
