# Generated by Django 4.1.1 on 2022-10-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_lesson_options_alter_lesson_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
    ]
