# Generated by Django 4.1.1 on 2022-12-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0011_alter_lesson_options_alter_lesson_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Public'),
        ),
    ]
