# Generated by Django 4.1.1 on 2022-12-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0012_lesson_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Lesson slug'),
        ),
    ]
