# Generated by Django 4.1.1 on 2022-12-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_alter_lesson_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='Lesson slug'),
        ),
    ]
